### ISSUE TITLE
Acessing the this of the component

### ISSUE THREAD

**Issue by weslley39** [ngReact/ngReact#139]
I'm using this component [react-calendar-timeline](https://github.com/namespace-ee/react-calendar-timeline), and implementing this way:

```
$scope.props =
        sidebarWidth: 1
        dragSnap: 1000
        lineHeight: 60
        groups: [
          {
            id: "formatos"
            title: "Formato"
          },
          {
            id: "programas"
            title: "Programas"
          }
        ]
        items: []
        fixedHeader: "absolute"
        canMove: yes
        canResize: no
        itemTouchSendsClick: no
        canChangeGroup: no

        defaultTimeStart: $scope.defaultTimeStart.toDate()
        defaultTimeEnd: $scope.defaultTimeEnd.toDate()

        visibleTimeStart: date.valueOf()
        visibleTimeEnd: date.add(1, 'd').valueOf()
        keys:
          groupIdKey: "id"
          groupTitleKey: "title"
          itemIdKey: "id"
          itemTitleKey: "title"
          itemGroupKey: "group"
          itemTimeStartKey: "start"
          itemTimeEndKey: "end"
          itemColor: "color"

        onItemResize: (item, newResizeEnd) ->
          item = findItem(item)
          item.end = newResizeEnd
```

in the .html i have:
```
<react-component name="ReactCalendarTimeline" props="props" watch-depth="reference"/>
```

i'm having an issue, accessing the `this` inside the component, like, the component has a method called `updateScrollCanvas`, if i try `this.updateScrollCanvas`, inside of the function `onItemResize`, i can't access this function, any help ?
